export interface Review {
  id: string;
  productSlug: string;
  author: string;
  rating: number;
  title: string;
  body: string;
  date: string;
  featured?: boolean;
}

export const reviews: Review[] = [
  {
    id: "r-bk-1",
    productSlug: "bitter-kola",
    author: "Ada O.",
    rating: 5,
    title: "Just like back home",
    body: "Fresh, firm and properly bitter — exactly what I grew up with. Fast delivery too.",
    date: "2026-04-02",
    featured: true,
  },
  {
    id: "r-bk-2",
    productSlug: "bitter-kola",
    author: "Femi A.",
    rating: 4,
    title: "Good quality",
    body: "Nice size nuts, well packaged. Would order again.",
    date: "2026-03-18",
  },
  {
    id: "r-bk-3",
    productSlug: "bitter-kola",
    author: "Grace N.",
    rating: 5,
    title: "Reliable supplier",
    body: "This is my third order — consistently fresh every time.",
    date: "2026-02-27",
  },
  {
    id: "r-ap-1",
    productSlug: "alligator-pepper",
    author: "Kwame B.",
    rating: 5,
    title: "Great aroma",
    body: "Really fragrant pods, not dusty or old like some I've bought before.",
    date: "2026-04-11",
  },
  {
    id: "r-ap-2",
    productSlug: "alligator-pepper",
    author: "Chioma E.",
    rating: 4,
    title: "As described",
    body: "Good flavour, arrived well sealed. Will buy again for the next ceremony.",
    date: "2026-03-09",
  },
  {
    id: "r-ap-3",
    productSlug: "alligator-pepper",
    author: "Tunde S.",
    rating: 5,
    title: "Excellent",
    body: "Exactly what I needed, and the packaging kept everything fresh in transit.",
    date: "2026-01-22",
  },
  {
    id: "r-dbl-1",
    productSlug: "dry-bitter-leaf",
    author: "Ngozi P.",
    rating: 5,
    title: "Saves so much time",
    body: "Already washed and dried — cuts my prep time right down. Tastes great in soup.",
    date: "2026-04-20",
    featured: true,
  },
  {
    id: "r-dbl-2",
    productSlug: "dry-bitter-leaf",
    author: "Samuel K.",
    rating: 4,
    title: "Good but goes fast",
    body: "Great quality leaves, just wish the bag was a bit bigger for the price.",
    date: "2026-03-30",
  },
  {
    id: "r-dbl-3",
    productSlug: "dry-bitter-leaf",
    author: "Bisi T.",
    rating: 5,
    title: "Very fresh",
    body: "Rehydrated beautifully, proper bitter leaf taste. Highly recommend.",
    date: "2026-02-14",
  },
  {
    id: "r-bp-1",
    productSlug: "black-pepper",
    author: "Ola J.",
    rating: 5,
    title: "Great for grinding fresh",
    body: "Peppercorns are plump and fragrant, big difference from the supermarket jar.",
    date: "2026-04-14",
  },
  {
    id: "r-bp-2",
    productSlug: "black-pepper",
    author: "Ruth I.",
    rating: 4,
    title: "Reliable staple",
    body: "Does exactly what it should. Good value for the quantity.",
    date: "2026-02-19",
  },
  {
    id: "r-bl-1",
    productSlug: "bay-leaf",
    author: "Emeka C.",
    rating: 5,
    title: "Fragrant and fresh",
    body: "Much more aromatic than what I've bought in shops before.",
    date: "2026-03-27",
  },
  {
    id: "r-bl-2",
    productSlug: "bay-leaf",
    author: "Funmi L.",
    rating: 4,
    title: "Good quality leaves",
    body: "Whole leaves, not crushed or broken. Works great in my stew pot.",
    date: "2026-01-30",
  },
  {
    id: "r-psk-1",
    productSlug: "pepper-soup-kit",
    author: "Michael T.",
    rating: 5,
    title: "Restaurant quality at home",
    body: "So easy to use and the flavour is spot on. My family loved it.",
    date: "2026-04-22",
    featured: true,
  },
  {
    id: "r-psk-2",
    productSlug: "pepper-soup-kit",
    author: "Ijeoma V.",
    rating: 5,
    title: "Perfect for a cold evening",
    body: "Took the guesswork out completely, tasted like my mum's recipe.",
    date: "2026-03-21",
  },
  {
    id: "r-psk-3",
    productSlug: "pepper-soup-kit",
    author: "Bayo H.",
    rating: 4,
    title: "Very good kit",
    body: "Great balance of spices, just add your meat and veg.",
    date: "2026-02-03",
  },
  {
    id: "r-kl-1",
    productSlug: "kilishi",
    author: "Aisha M.",
    rating: 5,
    title: "Tastes exactly right",
    body: "Proper peppery crust and chewy texture, just like the kilishi from the market back home.",
    date: "2026-05-03",
    featured: true,
  },
  {
    id: "r-kl-2",
    productSlug: "kilishi",
    author: "Emeka O.",
    rating: 5,
    title: "Addictive snack",
    body: "Didn't expect to finish the whole pack in one sitting but here we are. Great heat level.",
    date: "2026-04-19",
  },
  {
    id: "r-kl-3",
    productSlug: "kilishi",
    author: "Sarah P.",
    rating: 4,
    title: "Good quality, a bit pricey",
    body: "Really flavourful and well spiced, just wish the pack was a touch bigger.",
    date: "2026-03-08",
  },
  {
    id: "r-ss-1",
    productSlug: "suya-spice",
    author: "Tobi A.",
    rating: 5,
    title: "Nails the flavour",
    body: "Rubbed this on chicken skewers and it tasted just like suya from the roadside grills.",
    date: "2026-05-11",
  },
  {
    id: "r-ss-2",
    productSlug: "suya-spice",
    author: "Grace K.",
    rating: 5,
    title: "Smoky and nutty",
    body: "Great balance of peanut and pepper, works well on vegetables too.",
    date: "2026-04-02",
  },
  {
    id: "r-ss-3",
    productSlug: "suya-spice",
    author: "Ben O.",
    rating: 4,
    title: "Solid blend",
    body: "Good heat, good aroma. Will be my go-to for barbecue season.",
    date: "2026-02-21",
  },
  {
    id: "r-ge-1",
    productSlug: "ground-egusi",
    author: "Nneka I.",
    rating: 5,
    title: "Fine and fresh",
    body: "Grinds smoothly into the soup, no lumps, and tastes properly nutty.",
    date: "2026-05-06",
    featured: true,
  },
  {
    id: "r-ge-2",
    productSlug: "ground-egusi",
    author: "Femi D.",
    rating: 4,
    title: "Good base for egusi soup",
    body: "Thickened up nicely, though I added a bit more than the packet suggested.",
    date: "2026-03-27",
  },
  {
    id: "r-ge-3",
    productSlug: "ground-egusi",
    author: "Patience U.",
    rating: 5,
    title: "Just like home",
    body: "Perfect texture and flavour, my egusi soup has never tasted better.",
    date: "2026-02-14",
  },
  {
    id: "r-go-1",
    productSlug: "ground-ogbono",
    author: "Chinedu L.",
    rating: 5,
    title: "Rich and silky",
    body: "Gave my draw soup exactly the texture I was after. Great quality grind.",
    date: "2026-05-15",
  },
  {
    id: "r-go-2",
    productSlug: "ground-ogbono",
    author: "Ifeoma B.",
    rating: 4,
    title: "Very good",
    body: "Fresh smell, worked well in the pot. Would buy again.",
    date: "2026-04-08",
  },
  {
    id: "r-go-3",
    productSlug: "ground-ogbono",
    author: "Richard N.",
    rating: 5,
    title: "Excellent draw",
    body: "Exactly the consistency I remember from my mother's cooking.",
    date: "2026-03-01",
  },
  {
    id: "r-cay-1",
    productSlug: "cayenne-pepper",
    author: "Laura H.",
    rating: 5,
    title: "Clean, steady heat",
    body: "Not overwhelming, just a good consistent kick. Love that it's organic too.",
    date: "2026-05-20",
  },
  {
    id: "r-cay-2",
    productSlug: "cayenne-pepper",
    author: "Michael R.",
    rating: 4,
    title: "Good everyday pepper",
    body: "Fine grind, works well in marinades and sauces alike.",
    date: "2026-04-25",
  },
  {
    id: "r-cay-3",
    productSlug: "cayenne-pepper",
    author: "Deborah S.",
    rating: 5,
    title: "Great quality",
    body: "Vibrant colour and properly fresh heat, noticeably better than supermarket brands.",
    date: "2026-03-14",
  },
  {
    id: "r-hib-1",
    productSlug: "hibiscus-flower",
    author: "Folake A.",
    rating: 5,
    title: "Best zobo I've made",
    body: "Deep colour and properly tangy, exactly like the dried hibiscus back home.",
    date: "2026-06-02",
    featured: true,
  },
  {
    id: "r-hib-2",
    productSlug: "hibiscus-flower",
    author: "Rachel T.",
    rating: 5,
    title: "Lovely for iced tea",
    body: "Steeps beautifully and the flavour is strong, didn't need much per jug.",
    date: "2026-05-18",
  },
  {
    id: "r-hib-3",
    productSlug: "hibiscus-flower",
    author: "Ben K.",
    rating: 4,
    title: "Good quality, great colour",
    body: "Really vibrant petals, clearly well dried. Will order again for the summer.",
    date: "2026-04-30",
  },
];

export function getReviewsBySlug(slug: string): Review[] {
  return reviews.filter((r) => r.productSlug === slug);
}

export function getAverageRating(slug: string): number {
  const productReviews = getReviewsBySlug(slug);
  if (productReviews.length === 0) return 0;
  const total = productReviews.reduce((sum, r) => sum + r.rating, 0);
  return Math.round((total / productReviews.length) * 10) / 10;
}

export function getFeaturedReviews(): Review[] {
  return reviews.filter((r) => r.featured);
}
